### ISSUE TITLE
Package source on the FoundryVTT page redirects to old git

### ISSUE THREAD

**Issue by Krigsmaskine** [esheyw/find-the-culprit#1]
Thanks for picking up the module!

I was curious about your changes and noticed the Project Source still links to the Moerill's old git on Foundry's package page. Unsure if that's within your control, but figured I'd give a headsup. I was confused about the maintenance mode message, at least. 😄 

https://foundryvtt.com/packages/find-the-culprit
![image](https://github.com/esheyw/find-the-culprit/assets/39592771/2ead75ce-cfff-498d-85af-c72b75d987b1)

**Comment by cs96and** [comment]
Also the "Read Notes" link for 1.5.0 doesn't work

![image](https://github.com/esheyw/find-the-culprit/assets/898086/0ba9f33e-89df-4b02-8d5b-df9e8acb2815)

**Comment by esheyw** [comment]
These should all be fixed now. Let me know if I missed something!
