### ISSUE TITLE
Can't get out of testing mode

### ISSUE THREAD

**Issue by ctbritt** [esheyw/find-the-culprit#10]
I don't know what i did, but in dnd5e 4.0.3 and FTC 3.0, I can't get out of testing mode. If I have FTC enabled, every time I refresh my world I get the below warning: 

![CleanShot 2024-09-24 at 22 20 13@2x](https://github.com/user-attachments/assets/ec44dd4b-95b3-4331-9e44-c86e6c3c9ae5)

If i close the window or click the rest button, it refreshes. If I leave it open and enable or disable modules manually, then click save, it repeats and all the modules I toggled off are back to their state before. 

Here are some error messages:
![CleanShot 2024-09-24 at 22 22 22@2x](https://github.com/user-attachments/assets/b8785bad-9d8d-4f4d-9b86-bf62f22f1cc5)
![CleanShot 2024-09-24 at 22 22 46@2x](https://github.com/user-attachments/assets/7dc232f6-cb49-4234-8585-349e3079555f)

Is there some way to erase the FTC data? 

help! 
C

**Comment by esheyw** [comment]
Just out of curiosity, *was* your world in a state where one module was active but its dependency wasn't, before installing FtC 3.0? I was hoping that was going to be exceedingly rare but considering the part where old FtC regularly did this I suppose I should have known better. 

I will have to think about how to best mitigate this, and probably have to fail more gracefully here.

My quick fix advice is to uninstall FtC, load back into that world, fix your modules such that things have all their dependencies enabled, and run this in the console:
```js
game.settings.storage.get('world').filter(s=>s.key.startsWith('find-the-culprit')).forEach(s => s.delete())
```
then reinstall

**Comment by esheyw** [comment]
Also if you want to right click on 'modules' in the data dump, copy object, and post that here or preferably DM me on discord (ID's the same, `esheyw`, you can find me on the [Foundry official discord](https://discord.gg/foundryvtt)

**Comment by ctbritt** [comment]
Your `game.settings...` did the trick. That cleaned it up. As for your question, I don't really know.  But it seems all right now.

**Comment by esheyw** [comment]
Assuming you've not had any problems since then, I'm gonna close this. The new handling for such a state in 3.1 should be much more robust.
