### ISSUE TITLE
Entrie from pt-BR

### ISSUE THREAD

**Issue by Kharmans** [esheyw/find-the-culprit#11]
You forgot to add the entrie on module.json to pt-BR hehe. It has to be like the bellow.

```js
        {
            "lang": "pt-BR",
            "name": "Português (Brasil)",
            "path": "lang/pt-BR.json",
            "flags": {}
        }
```

**Comment by esheyw** [comment]
Hey, yea, my bad. I just assumed you'd added that as part of the PR and didn't check closely. It's added now.
This update also added to the en.json, aaaand I also deep sorted it, which will probably be annoying when looking at the diff. Sorry.
