### ISSUE TITLE
Issue under V12 with Forge hosting

### ISSUE THREAD

**Issue by LordOHelmet** [esheyw/find-the-culprit#2]
My games are hosted on the Forge.

When I try to execute `Find the culprit` nothing happens.

![Culprit](https://github.com/esheyw/find-the-culprit/assets/80178910/84252cd6-8378-4d72-8c4b-92ae3cbf0947)

**Comment by esheyw** [comment]
So this was not a Forge issue, as I initially assumed, but *something* was apparently causing a file to be renamed during the release process? maybe? and sometimes some other templates just didn't ship? No clue how or why. A new release is out, that should not have been necessary, but please test and see if it fixes the issue for you.

**Comment by LordOHelmet** [comment]
Great! Works fine now on my end.
Thanks for keeping up the work!
