### ISSUE TITLE
FTC Ends a Diagnostic Prematurely

### ISSUE THREAD

**Issue by Armandeus66** [esheyw/find-the-culprit#6]
Thanks for your work on this very useful module.

"If the issue persists, the module will start a binary search by only reactivating half of your previously active modules, refreshing the page, going on like this until the culprit is found."

1. I start FTC with no modules selected, press start, and there is a refresh.
2. Foundry starts with no modules. I click "no," the issue doesn't persist. There is a refresh.
3. Foundry starts with the first half of the module list enabled (I looked at Module Management). I click "yes" the issue persists.
4. Instead of continuing the diagnostic, FTC tells me it must be a problem with the system or Foundry itself, and then ends the diagnostic, asking me to refresh so all modules can be reactivated.

Foundry v. 12.329, Pathfinder 2E v. 6.1.0, FTC v. 2.1.3, Chrome v. 126.0.6478.128

**Comment by esheyw** [comment]
Hi, sorry for missing this, I haven't been getting notifications properly for this repo. 

I just released version 3.0 which is an almost complete rewrite. If you *were* still experiencing this, please try the current version and report back.

**Comment by Armandeus66** [comment]
Thank you!

**Comment by esheyw** [comment]
Going to close this now, please open a new issue if you experience additional problems.
